version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "${PORT}:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf
    depends_on:
      - app_blue
      - app_green
  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:3000"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:3000"
