version: '3.8'

services:
  blue:
    image: ${BLUE_IMAGE}
    container_name: app-blue
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  green:
    image: ${GREEN_IMAGE}
    container_name: app-green
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-reverseproxy
    ports:
      - "${PORT:-8080}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - blue
      - green
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge